# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IHPMIj0SJYPQr6QQoxmFvpVH5Xz1xfT
"""

# Q1 Write a program that takes an integer input from the user and checks whether the number is odd or even.
x=int(input())
if x % 2==0:
  print("even")
else:
  print("odd")

# Q2 Write a program that takes three numbers as input and prints the largest of the three.
x=int(input())
y=int(input())
z=int(input())
if x > y and x > z:
  print(" a is greater")
elif y > x and y > z:
  print("b is greater")
else:
  print("c is greater")

# Write a program to check if a given year is a leap year. A leap year is divisible by 4 but not by 100
# unless it is also divisible by 400.
x=int(input())
if x%4==0 and x%100!=0:
  print("leap year")
elif x%400==0 and x%100==0:
  print("leap year")
else:
  print("not")

# Q4 Write a program that takes a percentage (integer) as input and prints the corresponding grade based
# on the following criteria:
# >= 90: Grade A
# >= 80: Grade B
# >= 70: Grade C
# >= 60: Grade D
# < 60: Grade F
x=int(input())
if x>=90:
  print("grade a")
elif x>=80:
  print("grade b")
elif x>=70:
  print("grade c")
elif x>=60:
  print("grade d")
elif x>=50:
  print("grade f")
else:
  print("fail")

# Q5 Write a program that checks if a given letter is a vowel (a, e, i, o, u) or a consonant.
x=input()
s='aeiou'
if x in s:
  print("vowel")
else:
  print("consonent")

# Q6 Write a basic calculator program that takes two numbers and an operator (+, -, *, /) as input and
# performs the specified operation. Print the result based on the operation.
x=int(input())
y=int(input())
if

# Write a program that takes a number as input and checks whether it is positive, negative, or zero.
x=int(input())
if x>0:
  print('positive')
elif x<0:
  print('negative')
else:
  print('zero')

# Q8 Write a program that checks if a username and password entered by the user match the pre-set values
# username = "admin" and password = "1234". If both match, print "Login Successful", otherwise print
# "Login Failed".
username=input()
password=int(input())
if username=='admin' and password==1234:
  print('login successful')
else:
  print('login failed')

# Q9 Write a program that takes three sides of a triangle as input and checks if those sides form a valid
# triangle. A triangle is valid if the sum of any two sides is greater than the third side.
# Check conditions like a + b > c, b + c > a, and a + c > b.
a=int(input())
b=int(input())
c=int(input())
if a+b>c and b+c>a and a+c>b:
  print('valid')
else:
  print('not')

# Q10 Write a program that calculates the Body Mass Index (BMI) based on user input for weight (in
# kilograms) and height (in meters). Then categorize the BMI into:
# Underweight (BMI < 18.5)
# Normal weight (18.5 <= BMI < 24.9)
# Overweight (25 <= BMI < 29.9)
# Obesity (BMI >= 30)
# Use the formula: BMI = weight / (height ** 2)
w=int(input('rajat weight'))
h=float(input('rajat data scientist'))
BMI = w / (h**2)
if BMI < 18.5:
  print('underweight')
elif 18.5 <= BMI < 24.9:
  print('normal weight')
elif 25 <= BMI < 29.9:
  print('overweight')
elif BMI >=30:
  print('obessity')
else:
  print('invalid')

# Q11 Write a program that calculates the discount for a product based on its price:
# If price is greater than 1000, discount is 10%
# If price is between 500 and 1000, discount is 5%
# Otherwise, no discount
# Print the final price after applying the discount.
p=int(input())